services:
  - type: web
    name: george-chatbot
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: python -m uvicorn server.app:app --host 0.0.0.0 --port $PORT
